name: wazo-chatd-reactions
namespace: community
version: 1.1.1
author: Community
display_name: Chat Message Reactions & Replies
description: Add emoji reactions and threaded replies to chat messages in Wazo
min_wazo_version: 23.01
plugin_format_version: 1
tags:
  - chat
  - chatd
  - reactions
  - emoji
  - replies
  - threads
homepage: https://github.com/Hubelia/wazo-chatd-reactions
